"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.kCodapAppElementId = exports.kDefaultTileHeight = exports.kDefaultTileWidth = exports.kTitleBarHeight = exports.defaultTileTitleFont = exports.defaultItalicFont = exports.defaultBoldFont = exports.defaultFont = exports.defaultFontSize = exports.defaultFontStack = void 0;
exports.defaultFontStack = "Lato, sans-serif";
exports.defaultFontSize = "14px";
exports.defaultFont = "".concat(exports.defaultFontSize, " ").concat(exports.defaultFontStack);
exports.defaultBoldFont = "bold ".concat(exports.defaultFont);
exports.defaultItalicFont = "italic ".concat(exports.defaultFont);
exports.defaultTileTitleFont = exports.defaultItalicFont;
exports.kTitleBarHeight = 25;
exports.kDefaultTileWidth = 250;
exports.kDefaultTileHeight = 250;
exports.kCodapAppElementId = "codap-app-id";
