name: Playwright Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps --no-shell chromium
    - name: Run Playwright tests
      run: npx playwright test
      env:
        PLAYWRIGHT_CI: "true"
    # Once the s3 upload works we can probably get rid of this
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        flags: playwright
        token: ${{ secrets.CODECOV_TOKEN }}    
    - uses: concord-consortium/s3-deploy-action/deploy-path@v1
      if: always()
      id: s3-deploy-path
    - name: Upload Playwright Report
      if: always()
      run: aws s3 sync ./playwright-report s3://models-resources/dst-codap-plugin/playwright-report/${{ steps.s3-deploy-path.outputs.deployPath }} --delete --cache-control "no-cache, max-age=0"
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # This currently fails with: "No PR associated with this action run. Not posting a check or comment."
    # That happens because we are triggering not on the PR but on the push.
    # However it is possible to figure out the PR because the codecov and cypress actions are doing it.
    # We stopped using the trigger on PR because that was breaking the s3-deploy-action
    # So either we fix that action or we fix this one.
    - uses: daun/playwright-report-summary@v3
      if: always()
      with:
        report-file: results.json
        report-url: https://models-resources.concord.org/dst-codap-plugin/playwright-report/${{ steps.s3-deploy-path.outputs.deployPath }}/
